export type RootStackParamList = {
    RegisterScreen: undefined;
    LoginScreen: undefined;
    HomeScreen: undefined;
    DemandeLogementScreen: undefined;
    HebergementUrgenceScreen: undefined;
    SoutienPsychologiqueScreen: undefined;
    DemandeUrgenceScreen: undefined;
    CentreAideScreen: undefined;
    ActualitesScreen: undefined;
    ResourcesUrgenceScreen: undefined;
    VictimeFeminicideScreen: undefined;
    FamilleEndeuilleScreen: undefined;
    EmergencyHousingScreen: undefined;
    ProfileScreen: undefined;
    SecuritySettingsScreen: undefined;
    FeedbackScreen: undefined;
    SupportScreen: undefined;
    MessagerieScreen: undefined;
    ContactScreen: undefined;
    ParametreScreen: undefined;
}; 